# Generated by Django 5.0.4 on 2024-05-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_session_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
