# Generated by Django 5.0.4 on 2024-05-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_coursesubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesubscription',
            options={'verbose_name': 'подписка на курс', 'verbose_name_plural': 'подписки на курсы'},
        ),
    ]
